# Generated by Django 5.0.4 on 2024-08-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('br', 'Bedroom'), ('dn', 'Dining'), ('of', 'Office'), ('lr', 'Livingroom')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
