# Generated by Django 5.0.4 on 2024-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
