# Generated by Django 5.0.4 on 2024-08-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_good_accessories_good_color_good_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='wepth',
            new_name='depth',
        ),
    ]
